In [1]:
import torch

In [2]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [3]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [5]:
x=torch.tensor([1,2,4,8])
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [13]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [15]:
before=id(1)
Y=1+2
id(Y)==before

False

In [18]:
X=torch.tensor([1,2,4,8])
Y=torch.tensor([1,3,4,8])
before=id(X)
Y=X+Y
id(Y)==before

False

In [19]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)


(numpy.ndarray, torch.Tensor)

In [20]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [6]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('1,Pave,127500\n')
    f.write('2,Pave,127500\n')
    f.write('3,Pave,127500\n')

In [7]:
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       1.0  Pave  127500
2       2.0  Pave  127500
3       3.0  Pave  127500


In [8]:
#为了处理缺失的数据，插值和删除
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]   # iloc取出来赋给输入输出
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       2.0  Pave
1       1.0  Pave
2       2.0  Pave
3       3.0  Pave


C:\Users\Emperor\AppData\Local\Temp\ipykernel_14736\1661454261.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs=inputs.fillna(inputs.mean())


In [13]:
inputs=pd.get_dummies(inputs,dummy_na=True)   # 默认转了以后的变量用其他名字表示



In [16]:
import torch
X1,Y1=torch.tensor(inputs.values),torch.tensor(outputs.values)
X1,Y1   # 所有条目转换为张量模式

(tensor([[2., 1., 0.],
         [1., 1., 0.],
         [2., 1., 0.],
         [3., 1., 0.]], dtype=torch.float64),
 tensor([127500, 127500, 127500, 127500]))

In [3]:
import torch  
a=torch.arange(12)
b=a.reshape((3,4))
b[:]=2    # 使用切片创建视图修改数据会影响到原始数组    对称矩阵总是能找到特征向量
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [2]:
import torch
x=torch.tensor([4.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([6.]), tensor([8.]), tensor([2.]), tensor([16.]))

In [3]:
A=torch.arange(40).reshape(2,5,4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [5]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [6]:
torch.abs(u).sum()  # L1范数

tensor(7.)

In [14]:
import torch
x=torch.arange(4.0)
x.requires_grad_(True)
x.grad
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [15]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [16]:
x.grad==4*x

tensor([True, True, True, True])

In [20]:
# 在默认情况下，pytorch会累积梯度，我们要清除之前的值
# x.grad.zero_()   注释掉会累加
y=x.sum()
y.backward()
x.grad

tensor([2., 2., 2., 2.])

In [21]:
# 对非标量调用backward需要传入一个gradient参数
x.grad.zero_()
y=x*x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [6]:
# 为什么获取.grad前需要backward :节省内存
X=torch.normal(0,1,(1000,2)
print(X)

SyntaxError: invalid syntax (3380460952.py, line 3)